### ISSUE TITLE
Add user option to composer::project

### ISSUE THREAD

**Issue by mbrodala** [Brainsware/puppet-composer#10]
ATM `composer::project` is evaluated with user `root` which has disadvantages:

1. Usually SSH keys for repository access are not set up for `root` but for a regular user instead: `create-project` command fails on private repositories.
2. The created directory is owned by `root`: ownership has to be changed to an unprivileged user.

Thus a `$user` option (which may default to `$composer::params::user`) should be added which is applied to all `exec` resources within `composer::project`.

**Comment by igalic** [comment]
+1
@mbrodala do you wanna propose your own pr?

**Comment by mbrodala** [comment]
Sure but first I'd like to get #9 merged to avoid rebasing issues. ;-)

**Comment by igalic** [comment]
let's get this one in too, and then make a new release!

**Comment by mbrodala** [comment]
I'll give it a try in the next days. :-)
