### ISSUE TITLE
Add option to set COMPOSER_HOME

### ISSUE THREAD

**Issue by mbrodala** [Brainsware/puppet-composer#12]
Instead of the fallback to `HOME/.composer` one can explicitly set `COMPOSER_HOME`. This should be an option.

I'm not sure about the best location though. Both `composer::$home` and `composer::project::$home` come into mind where the former actually makes more sense but would make it harder for `composer::project` to use.

Suggestions?

**Comment by igalic** [comment]
we could set the option in composer::home, and re-use it as default in composer::project

**Comment by mbrodala** [comment]
So you mean defaulting to `$composer::home` instead of `$composer::params::home`?

**Comment by igalic** [comment]
i'm starting to doubt the usfulness of `composer::params`.

generally, the hierarchy is:

`composer::project::foo` ← `composer::foo` ← `composer::params::foo` = 'bare constant'

however, composer::params, as a pattern, only makes sense if we're supposed to support (widely) different systems, where these params *actually* differ.

as it is, we can simplify this chain down to:

`composer::project::foo` ← `composer::foo` = 'bare constant'

**Comment by mbrodala** [comment]
Alright, I'll gladly go with this.

**Comment by igalic** [comment]
well, then, please prepare a pull request!

**Comment by mbrodala** [comment]
Apparently the current solution yields a warning in case `$composer::home` is not set:

> `Warning: Exec[composer-fix-permissions](provider=posix): Cannot understand environment setting "COMPOSER_HOME="`

Gotta tweak this.

**Comment by igalic** [comment]
i think we should establish Pull Requests for everything.
(me too)

**Comment by mbrodala** [comment]
Yeah, usually going via PR should be preferred, especially to wait for Travis confirmation. But in this case I have tried it locally on a development setup to actually develop the fix. ;-)

**Comment by igalic** [comment]
*nod*
