### ISSUE TITLE
composer should be downloaded via https

### ISSUE THREAD

**Issue by igalic** [Brainsware/puppet-composer#13]
for *some* integrity, we should download composer via https://

**Comment by igalic** [comment]
done in 30ee18124385c177063156e9c77ef4088a6c080c

**Comment by igalic** [comment]
probz should do another release here?
ping @mbrodala.

**Comment by mbrodala** [comment]
Go ahead. :+1: for dropping `$composer::params`.

**Comment by igalic** [comment]
0.2.5 released and pushed to forge!
