### ISSUE TITLE
composer now outputs to stderr

### ISSUE THREAD

**Issue by stunami** [Brainsware/puppet-composer#19]
Hi,

composer recently changed to output from using stdout to stderr as you can see from this PR

https://github.com/composer/composer/pull/3715/files

this breaks composer::project as the grep fails on the onlyif

https://github.com/Brainsware/puppet-composer/blob/master/manifests/project.pp#L125

```
  exec { "composer_install_${title}":
    command => "${composer} install ${base_opts} ${install_opts}",
    onlyif  => "${composer} install ${install_opts} --dry-run | grep -E -- '- (Install|Updat)ing '",
  }
```

Piping stderr to stdout fixes this as below, though I haven't tested it with older composer versions.

````
    onlyif  => "${composer} install ${install_opts} --dry-run 2>&1 >/dev/null | grep -E -- '- (Install|Updat)ing '",

```

**Comment by mbrodala** [comment]
What's the `>/dev/null` in your fix for? This drops everything (stdout & stderr) thus this command can never succeed.

The general redirection of stderr to stdout to have its output available for pattern matching looks fine though.

If this was executed on an older Composer version and a real error occurred, the pattern match would just not succeed which is the same as if all required packages are already installed.

**Comment by mbrodala** [comment]
Uh, apparently `>/dev/null` only drops the original stdout, not the stderr redirected to stdout. But this would break on older Composer versions where the output went to stdout.

Thus without this part, this check should work on both old and new Composer versions.

**Comment by stunami** [comment]
Yeah I figured it wasn't the complete solution which is why there was no PR from me.

According to the composer dev's the correct check is the exit code https://github.com/composer/composer/issues/3795#issuecomment-76402512

**Comment by mbrodala** [comment]
Yeah, if we where checking for an error. But in both cases (packages installed/updated or nothing) the exit code is 0, so nothing we can check for.

**Comment by yakatz** [comment]
Will this make it into a release anytime soon?
The version on puppetforge needs this.

**Comment by mbrodala** [comment]
There are some refactoring steps outstanding before a new release can be made. You can pull this version explicitly e.g. in your `Puppetfile`:

```ruby
mod 'brainsware-composer',
  :git => 'git://github.com/Brainsware/puppet-composer.git',
  :ref => 'f8b74dfdf9e5176eb586b897c84afaf89b94607b'
```

**Comment by igalic** [comment]
sorry for chiming in so late: I can make a new release, OR, I make travis do it, so anyone with merge access can!

**Comment by goreilly** [comment]
I this project still maintained? I just encountered this error from the version (0.2.5) on puppet forge.

**Comment by mbrodala** [comment]
@goreilly Sure this is still maintained. See my previous comment to pull in the development version which fixes the issue. @igalic Maybe make a release with the current state after all?

**Comment by igalic** [comment]
will do!

**Comment by igalic** [comment]
released 0.2.6!

**Comment by mbrodala** [comment]
@igalic Thanks. :-)

**Comment by goreilly** [comment]
Thanks you guys :smile:
