### ISSUE TITLE
release 0.2.7

### ISSUE THREAD

**Issue by igalic** [Brainsware/puppet-composer#24]
before we release 0.2.7 of this module, I'd like to clarify a few things:
- manage deployment to forge with blacksmith + travis
- ensure everything is rubocop clean
- consider moving the module to @puppet-community

/cc @mbrodala @yakatz

**Comment by mbrodala** [comment]
I am also looking at #23 but haven't found time to do this yet.

**Comment by igalic** [comment]
we can safe #23 for (after) 1.0.0 ;)

**Comment by mbrodala** [comment]
Sure, I just wanted to avoid the whole deprecation process for `composer::repository`. But then again maybe we can just keep it and use it as convenience wrapper for `composer::config`.

**Comment by igalic** [comment]
whatever floats your boat.

we're in no hurry

**Comment by igalic** [comment]
interesting… so i just released 0.2.6

**Comment by igalic** [comment]
i have released 0.3.0 today
