### ISSUE TITLE
Make installing composer optional

### ISSUE THREAD

**Issue by philomory** [Brainsware/puppet-composer#33]
Some users may wish to use `composer::project` from this module, but are already using a different module (such as `puppet/php` by vox populi) to install composer. It'd be nice if you use specify `manage_install => false` or the equivalent to the `composer` class.

(Alternatively, you could make `composer::project` not auto-include the `composer` class at all, and it would be the user's responsibility to write `include composer` if they want to manage installing composer; but, that would presumably break existing code so maybe not the best plan at this point).

**Comment by mbrodala** [comment]
How about the feature added here: https://github.com/Brainsware/puppet-composer/commit/e78ab9c835a3024f31438c56486c71bee230b4f7

Exactly the mentioned example should work for your case.

**Comment by philomory** [comment]
Gah, not really sure how I missed that in the documentation. I'm still personally partial to allowing `provider => false` (or equivalent), but I guess it doesn't really matter.

As an aside, I actually discovered that because of the way `contains` works, `provider => []` does what I was aiming for (though I regard that more as a cute trick than something I'd want to actually use).
